#!/bin/bash -e

tmpdir=$(mktemp -d)
trap "rm -r $tmpdir" SIGINT SIGTERM EXIT
virtualenv $tmpdir
source $tmpdir/bin/activate
pip install --no-use-wheel --download pypi_download $(cat resources/python_packages.txt | tr '\n' ' ')
pip3.4 install --no-use-wheel --download pypi_download $(cat resources/python3_packages.txt | tr '\n' ' ')

cat <<EOF>tests/test_python_packages.sh
#!/bin/bash -e
# This file is generated by tools/20_download_python_packages.sh, do not edit.
EOF
for pypkg in $(cat resources/python_packages.txt); do
    if [[ $pypkg == *-* ]]; then
        continue
    fi
    echo "python -c \"import $pypkg\"">>tests/test_python_packages.sh
done
